### ISSUE TITLE
Power not working for some cases

### ISSUE THREAD

**Issue by Rousan99** [MathInspector/MathInspector#1]
As you can see here the power function is working
![Screenshot (48)](https://user-images.githubusercontent.com/51227331/79864110-81bc0d80-83f6-11ea-8144-5af2a2bddb0e.png)
But when i use the power in this array it is not working as you can see
![Screenshot (50)](https://user-images.githubusercontent.com/51227331/79864165-a0220900-83f6-11ea-92a9-0adcdc8a3cb3.png)
But it is again working for complex numbers
![Screenshot (51)](https://user-images.githubusercontent.com/51227331/79864208-b203ac00-83f6-11ea-8d8f-f116f19dd941.png)

Please fix the issue. I am using windows for operating this.

**Comment by MathInspector** [comment]
hmm, this is what I get, have you tried zooming out to confirm that the dots are not off screen to the right?  There are no labels on the axis in your second screenshot.  You can use the mousewheel to zoom in the graph window.
<img width="927" alt="Screen Shot 2020-04-21 at 10 10 43 AM" src="https://user-images.githubusercontent.com/60369559/79876047-8661d100-83b8-11ea-9a1d-44a3cec97c6c.png">

**Comment by Rousan99** [comment]
yes...i have zoomed it and it's still the same. Here is a screenshot
![Screenshot (52)](https://user-images.githubusercontent.com/51227331/79876791-1af41f80-8409-11ea-89f5-cbdea86a4083.png)

**Comment by MathInspector** [comment]
I have been able to reproduce this issue.  The current alpha-test windows build you are using is outdated.  The correct way to run the latest code is from the command line, following the instructions in the README about cloning the source

This issue has already been resolved in the latest code, but I was not actively supporting the windows build.  If this is very important to you, let me know and I can upload a new windows build with the latest to the mathinspector website.  Otherwise let's wait until some more contributors request changes of this type so I can gather all requests together and get them done in one shot.

Cheers!

**Comment by Rousan99** [comment]
Hi...I have downloaded from the GitHub. But the problem is "syslog" is making some error for Windows. 
"No module named 'syslog' (file: mathinspector.py line:27). Upon searching I found it's for Ubuntu. Can it be fixed or we can use it in Windows. Please provide some links or information 😅

**Comment by MathInspector** [comment]
This commit should resolve this issue.  Whoops!!!!  Sorry about that 🤦 
https://github.com/MathInspector/MathInspector/commit/c749caee1e3a95d5c3a7626471620589d4124672

**Comment by Rousan99** [comment]
Thanks....and there is another line...from where I have to remove syslog before using it.
https://github.com/MathInspector/MathInspector/blob/master/src/mathinspector.py#L27

**Comment by Rousan99** [comment]
As you can see, I am running the new version from github but it's still having the same problem with power function
![Screenshot (53)](https://user-images.githubusercontent.com/51227331/79935475-a3f37100-8472-11ea-98f0-686a5b9bad5d.png)

and **there is another problem i noticed** the left click is not working for windows. Well, It's not like a big problem as we can always use (left+mouse middle) but still i thought i should tell you.

**Comment by heliwave** [comment]
Please read this: https://www.rt.com/op-ed/486714-%D1%81ovid19-rich-americans-bunkers-new-zealand/
Then read this: http://heliwave.com/1433_EN.pdf in English or this http://heliwave.com/1433_CH.pdf in Chinese
Then tell me if they are related on not.
xie xie 


    On Wednesday, April 22, 2020, 05:57:32 AM GMT+3, Azazaya <notifications@github.com> wrote:  
 
 


As you can see, I am running the new version from github but it's still having the same problem with power function


and there is another problem i noticed the left click is not working for windows. Well, It's not like a big problem as we can always use (left+mouse middle) but still i thought i should tell you.

**Comment by heliwave** [comment]
Please read this: https://www.rt.com/op-ed/486714-%D1%81ovid19-rich-americans-bunkers-new-zealand/
Then read this: http://heliwave.com/1433_EN.pdf in English or this http://heliwave.com/1433_CH.pdf in Chinese
Then tell me if they are related on not.
xie xie 

    On Wednesday, April 22, 2020, 12:13:28 AM GMT+3, TheOneThreeSeven <notifications@github.com> wrote:  
 
 


This commit should resolve this issue. Whoops!!!! Sorry about that 🤦
c749cae

**Comment by MathInspector** [comment]
Are you still having this issue?  I had previously resolved the windows left click and the power issue, please feel free to close this if it has been resolved.  Otherwise I can transfer the fixes from the windows build that may not have been included in the source code release

**Comment by Rousan99** [comment]
Yes it's still have the click issue and the power one.

**Comment by heliwave** [comment]
Peace to you guys, this is rather important!
I am trying to post the following info online but google/YT seems to be blocking my posts.So for what is worth, I pass the info to you in case it become useful in the near future.
​Back in 2008, I found 31 events to sweep Earth along 31 latitudes, each lasting 4 days in the lunar year 1433AH (perhaps meteorite showers due to tail debris or magnetosphere anomalies).

Earth1433 free software allows the user to set the start date for the first event and browse through all 31 events to show which cities (>= 5000 people) are in the red, yellow, or green zone, or search for a city by its English name or local native name to show it on the world map with its danger-level color, population, and its latitude/longitude.

The source of this prediction is chapter 55 The Merciful (Ar-Rahmaan) which contains 78 verses, and 355 words which the same number as the number of days in an Islamic leap lunar year.
31 verses of the total 78 are the same 4 words phrase (فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ) which means "Then which of your Lord's bounties you (both man and jinn) still deny?".
These 31 repeated verses found between other sentences seem to point to 31 4-day periods within the lunar year. What will happen during these 31 standout periods is unknown but the numbers of these 31 verses ranging from 13 to 77 are 13 away from 0 to 90 on either side which seem to point to Earth latitudes from 13 to 77 degrees where Earth's latitudes range from 0 to 90 degrees.
http://heliwave.com/Earth1433.zip is an open software too to find out the danger cities and avoid them during their 4 days sweep.



xie xie :)
Ali AdamsGod > infinityhttp://heliwave.com










    On Sunday, April 26, 2020, 06:05:28 AM GMT+3, Azazaya <notifications@github.com> wrote:  
 
 

Yes it's still have the click issue and the power one.

**Comment by MathInspector** [comment]
I have just pushed a new commit to the master branch:
https://github.com/MathInspector/MathInspector/commit/c4a31ada6f8d480e7c9348faa83a39e6401a11f2

This fix should resolve the issues you are having with right clicking, you can also download version 0.1.4 of Math Inspector for windows from https://mathinspector.com/download.html

I have been able to reproduce all the issues you described and believe everything should be resolved, both for the windows .exe file, as well as when running from the source

Please let me know if this fix does not resolve these issues for you.
